app_current_date_main:
    path: /main
    controller: App\Controller\CurrentDateController::main

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number